// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"note_scheduler/config"
	"note_scheduler/controller"
	"note_scheduler/repository"
	"note_scheduler/service"
)

// Injectors from injector.go:

func InitializedActivityController() controller.ActivityController {
	db := config.SetupDatabaseConnection()
	activityRepositoryImpl := repository.NewActivityRepositoryImpl(db)
	scheduleRepositoryImpl := repository.NewScheduleRepositoryImpl(db)
	validate := validator.New()
	activityServiceImpl := service.NewActivityServiceImpl(activityRepositoryImpl, scheduleRepositoryImpl, validate)
	scheduleServiceImpl := service.NewScheduleServiceImpl(scheduleRepositoryImpl, validate)
	activityControllerImpl := controller.NewActivityControllerImpl(activityServiceImpl, scheduleServiceImpl)
	return activityControllerImpl
}

func InitializedScheduleController() controller.ScheduleController {
	db := config.SetupDatabaseConnection()
	scheduleRepositoryImpl := repository.NewScheduleRepositoryImpl(db)
	validate := validator.New()
	scheduleServiceImpl := service.NewScheduleServiceImpl(scheduleRepositoryImpl, validate)
	scheduleControllerImpl := controller.NewScheduleControllerImpl(scheduleServiceImpl)
	return scheduleControllerImpl
}

// injector.go:

var ActivitySet = wire.NewSet(repository.NewActivityRepositoryImpl, wire.Bind(new(repository.ActivityRepository), new(*repository.ActivityRepositoryImpl)), service.NewActivityServiceImpl, wire.Bind(new(service.ActivityService), new(*service.ActivityServiceImpl)), repository.NewScheduleRepositoryImpl, wire.Bind(new(repository.ScheduleRepository), new(*repository.ScheduleRepositoryImpl)), service.NewScheduleServiceImpl, wire.Bind(new(service.ScheduleService), new(*service.ScheduleServiceImpl)), controller.NewActivityControllerImpl, wire.Bind(new(controller.ActivityController), new(*controller.ActivityControllerImpl)))

var scheduleSet = wire.NewSet(repository.NewScheduleRepositoryImpl, wire.Bind(new(repository.ScheduleRepository), new(*repository.ScheduleRepositoryImpl)), service.NewScheduleServiceImpl, wire.Bind(new(service.ScheduleService), new(*service.ScheduleServiceImpl)), controller.NewScheduleControllerImpl, wire.Bind(new(controller.ScheduleController), new(*controller.ScheduleControllerImpl)))
